### ISSUE TITLE
loginButtons of undefined error due to new SSR feature

### ISSUE THREAD

**Issue by jbbr** [jedwards1211/meteor-webpack-react#90] opened 2015-10-10 11:33 UTC
The current master is broken because in the render() function references property `loginButtons` of non existing `Template` on the client.
That's because the workaround for the server somehow breaks Template variable for client ... I'm not quite sure why. Somehow the function scoped `var` assignment affects the clients global Template variable...

Problematic code:
```js
if (Meteor.isServer) {  
  // Template does not support server side
  var Template = {
    loginButtons: 'any'
  };
}
```

Adding something like `Template = {}` to the main_server.js failes too. Adding a package like `meteorhacks/meteor-ssr` which exports `Template` for server in a package.js fixes the undefined error (Maybe a package like this could be used to get <BlazeTemplate> SSR).

All in all: I think SSR is not really useful in the state its currently in the master as blaze is still used to render the base `meteor_core/meteor.html`. And as Blaze templates are rendered on the client SSR rendering.

I understand that it's a work in progress, thanks to @haydnhkim for this contribution! For me SSR is really important and I don't even need blaze SSR support. So it's very useful for me and I will try to get SSR with react-router working.
But maybe moving this feature to a feature branch and accepting merge request until it's useful would be better then having it incomplete in the master?

**Comment by haydnhkim** [comment] 2015-10-10 12:46
Sorry for my mistake. I have to check my code carefully.

**Comment by jbbr** [comment] 2015-10-10 13:05
No problem, thanks for the fix.
btw: have been able to somehow render the generated SSR output to DOM? e.g with `static-html` package instead of blaze

**Comment by jbbr** [comment] 2015-10-11 12:52
@haydnhkim Also broken: prod build because of babel config not in prod build script.
Possible solution: Move babel config object to a file and include in both dev and prod.

**Comment by haydnhkim** [comment] 2015-10-11 13:42
@jbbr Ok, this error be caused by different babel stage between .babelrc and webpack.config.client.js files.
just replace `babel` instead of `babel?stage=0` in webpack.config.client.js,then this simply fix might just solve the issue.
eg.
```
{
        test: /\.jsx?$/,
        loader: 'babel?stage=0',
        exclude: /node_modules|lib/,
}
```

**Comment by jbbr** [comment] 2015-10-11 13:44
Yes you are right. Thanks.
I first assumes that there are other configuration options in babel config which might be useful to be shared between server dev/prod & client dev/prod but it seems the only option is babel stage=0.
So it might not be worth introducing a common babel config just for this.

**Comment by jedwards1211** [comment] 2015-10-14 00:29
@jbbr Oh, shoot, you're totally right, I forgot that the server workaround would prevent other things like this from being on local scope.  How to get server-side source maps working...I'm not sure why I didn't see this issue before this PR though?

**Comment by jedwards1211** [comment] 2015-10-14 21:52
Okay, this is now fixed in the latest version of the branch: https://github.com/jedwards1211/meteor-webpack-react/tree/webpack-meteor-tools
I figured out a way to support server-side source maps without having to `require` in the server bundle.

**Closed** 2015-10-19 05:33 UTC
